// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC_UM9OufBjvf6LzMcotLNrmZrltbnRhU',
    appId: '1:26343599080:web:9dbc4aff489282a8d4125d',
    messagingSenderId: '26343599080',
    projectId: 'petpotal-d5fe6',
    authDomain: 'petpotal-d5fe6.firebaseapp.com',
    storageBucket: 'petpotal-d5fe6.firebasestorage.app',
    measurementId: 'G-X6H45V4557',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5RhrNNYhn7QyrIeR9CiAYmBAFLtMwSak',
    appId: '1:26343599080:android:8737475494088db8d4125d',
    messagingSenderId: '26343599080',
    projectId: 'petpotal-d5fe6',
    storageBucket: 'petpotal-d5fe6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1DyP35Aw9yi8XKpECQR01PchVPwSKWwI',
    appId: '1:26343599080:ios:40f5e1c54811a87dd4125d',
    messagingSenderId: '26343599080',
    projectId: 'petpotal-d5fe6',
    storageBucket: 'petpotal-d5fe6.firebasestorage.app',
    iosBundleId: 'com.example.petportal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1DyP35Aw9yi8XKpECQR01PchVPwSKWwI',
    appId: '1:26343599080:ios:40f5e1c54811a87dd4125d',
    messagingSenderId: '26343599080',
    projectId: 'petpotal-d5fe6',
    storageBucket: 'petpotal-d5fe6.firebasestorage.app',
    iosBundleId: 'com.example.petportal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC_UM9OufBjvf6LzMcotLNrmZrltbnRhU',
    appId: '1:26343599080:web:648daccefc5dabd6d4125d',
    messagingSenderId: '26343599080',
    projectId: 'petpotal-d5fe6',
    authDomain: 'petpotal-d5fe6.firebaseapp.com',
    storageBucket: 'petpotal-d5fe6.firebasestorage.app',
    measurementId: 'G-CFT1M9NNX7',
  );
}
